name: Bug Report
description: You think somethings is broken in the UI
title: "[Bug]: "
labels: ["bug"]
assignees: zero01101, seijihariki

body:
  - type: markdown
    attributes:
      value: |
        *Please complete this form with as much detailed information as possible.*
  - type: textarea
    id: what-did
    attributes:
      label: What happened?
      description: What happened that you weren't expecting, or what happened incorrectly?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Please provide us with precise step-by-step information on how to reproduce the issue
      value: |
        1. Go to .... 
        2. Press ....
        3. ... [etc]
    validations:
      required: true
  - type: textarea
    id: what-should
    attributes:
      label: What should have happened?
      description: Describe what you believe should have ocurred instead of what actually happened.
    validations:
      required: true
  - type: input
    id: commit
    attributes:
      label: Commit where the problem happens
      description: Which commit are you running? (i.e. https://github.com/zero01101/openOutpaint/commit/bf21c19ae352800d9e1b37bb490e817b6848e533, bf21c19)
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: What platforms do you use to access openOutpaint?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
        - iOS
        - Android
        - Other/Cloud
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers do you use to access the UI ?
      multiple: true
      options:
        - Mozilla Firefox
        - Google Chrome
        - Brave
        - Apple Safari
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: textarea
    id: browser-extensions
    attributes:
      label: Browser Extensions/Addons
      description: Please list all browser extensions/addons you have running.  Some have been known to cause issues with openOutpaint.
    validations:
      required: true
  - type: textarea
    id: webui-commandline
    attributes:
      label: AUTOMATIC1111 webUI Commandline Arguments
      description: Please list all used commandline arguments passed to A1111 webUI (i.e. `--api`).
    validations:
      required: true
  - type: textarea
    id: misc
    attributes:
      label: Additional information
      description: Please provide us with any relevant additional information, context, screenshots, etc.
