name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement"]
assignees: zero01101, seijihariki

body:
  - type: markdown
    attributes:
      value: |
        *Please complete this form with as much detailed information as possible.*
  - type: textarea
    id: related
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: feature
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen, preferably with example use-case scenario.
    validations:
      required: true
  - type: textarea
    id: workflow
    attributes:
      label: Proposed workflow
      description: Please provide us with step by step information on how you'd like the feature to be accessed and used
      value: |
        1. Go to .... 
        2. Press ....
        3. ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: misc
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
